dist: trusty
sudo: false

addons:
  apt:
    chrome: stable

branches:
  only:
    - develop

cache:
  directories:
    - ./node_modules

language: node_js
node_js:
  - '12'

install:
  - npm install

script:
  - ng lint
  - ng build
  # - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
