# This is a basic workflow to help you get started with Actions

name: Angular application

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build and Test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node 13.12.0
        uses: actions/setup-node@v1
        with:
          node-version: '13.12.0'

      # Runs a single command using the runners shell
      - name: Install dependances
        run: npm ci

      - name: Dotenv Action
        uses: c-py/action-dotenv-to-setenv@v1
        with:
          # the path to the .env file (including file name)
          env-file: '.env.example'

      # Runs a set of commands using the runners shell
      - name: Build
        run: npm run build:ci
      - name: Lint and Test
        run: |
          npm run lint

      # - name: Archive build
      #   if: success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: deploy_dist
      #     path: dist
      # - name: Archive code coverage result
      #   if: success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: deploy_coverage
      #     path: coverage
